name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:


  build:
    name:  ${{ matrix.python-version }} ${{ matrix.platform.os }}-${{ matrix.platform.python-architecture }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false  # If one platform fails, allow the rest to keep testing.
      matrix:
        python-version: [ 3.8]
        platform: [ os: "ubuntu-latest", python-architecture: "x64", rust-target: "x86_64-unknown-linux-gnu" ]


    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.platform.python-architecture }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.rust-target }}
          profile: minimal
          default: true

      - name: Install test dependencies
        run: pip install --upgrade tox setuptools

      - name: Install wheel (workaround python 3.10 CI issue)
        if: matrix.python-version == '3.10-dev'
        run: pip install --upgrade wheel

      - name: Build package
        run: pip install -e .

      - name: Test examples
        shell: bash
        env:
          PYTHON: ${{ matrix.python-version }}
        run: |
          for example_dir in examples/*; do
              tox -c $example_dir -e py
          done

      - name: Test sdist vendor Rust crates
        shell: bash
        run: |
          cd examples/namespace_package
          python setup.py sdist --vendor-crates
          cd dist
          tar -zxf namespace_package-0.1.0.tar.gz
          cd namespace_package-0.1.0
          cargo build --offline --target ${{ matrix.platform.rust-target }}
  test-abi3:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Rust aarch64-apple-darwin target
        if: matrix.os == 'macos-latest'
        run: rustup target add aarch64-apple-darwin

      - name: Build package
        run: pip install -e .

      - name: Build an abi3 wheel
        shell: bash
        run: |
          cd examples/rust_with_cffi/
          python --version
          pip install wheel
          python setup.py bdist_wheel --py-limited-api=cp36
          ls -la dist/
      # Now we switch to a differnet Python version and ensure we can install
      # the wheel we just built.
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install abi3 wheel and run tests
        shell: bash
        run: |
          cd examples/
          python --version
          pip install rust_with_cffi/dist/rust_with_cffi*.whl
          python -c "from rust_with_cffi import rust; assert rust.rust_func() == 14"
          python -c "from rust_with_cffi.cffi import lib; assert lib.cffi_func() == 15"
  test-cross-compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ target: "aarch64-unknown-linux-gnu", arch: "aarch64" ]
    steps:
      - uses: actions/checkout@master
      - name: Build Wheels
        run: |
          echo 'curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          source ~/.cargo/env
          rustup target add ${{ matrix.platform.target }}
          cd examples/rust_with_cffi/
          python3.6 -m pip install crossenv
          python3.6 -m crossenv "/opt/python/cp36-cp36m/bin/python3" --cc $TARGET_CC --cxx $TARGET_CXX --sysroot $TARGET_SYSROOT --env LIBRARY_PATH= --manylinux manylinux1 venv
          . venv/bin/activate
          build-pip install cffi wheel
          cross-expose cffi
          pip install wheel
          pip install -e ../../
          python setup.py bdist_wheel --py-limited-api=cp36
          ls -la dist/
          ' > build-wheels.sh
          docker run --rm -v "$PWD":/io -w /io messense/manylinux2014-cross:${{ matrix.platform.arch }} bash build-wheels.sh
      - name: Install abi3 wheel and run tests
        uses: uraimo/run-on-arch-action@v2.0.5
        with:
          arch: ${{ matrix.platform.arch }}
          distro: ubuntu20.04
          dockerRunArgs: |
            --volume "${PWD}/examples:/examples"
          install: |
            apt-get update
            apt-get install -y --no-install-recommends python3 python3-dev python3-pip build-essential libffi-dev
          run: |
            cd /examples
            python3 --version
            pip3 install rust_with_cffi/dist/rust_with_cffi*.whl
            python3 -c "from rust_with_cffi import rust; assert rust.rust_func() == 14"
            python3 -c "from rust_with_cffi.cffi import lib; assert lib.cffi_func() == 15"
